electron/brightray

- brightray.gyp
- browser/brightray_paths.h
- browser/browser_context.cc
- browser/browser_main_parts.cc
This gives users a chance to override the user data path, making https://github.com/atom/atom-shell/issues/647 possible.
> Use PathService to set and get DIR_USER_DATA

- brightray.gypi
libchromiumcontent uses [`libc++` library](https://github.com/brightray/libchromiumcontent/commit/7df5689ae2adf86bd3d75667cc85012e73938c88) since chrom39 on mac. We should also use the same library while building brightray, otherwise link error(undefined symbol) will occur.
> Use libc++ on mac.

- common/content_client.cc
- common/content_client.h
This patch will allow `brightray` users(AtomShell) to access some Chrome's webuis, such as chrome://gpu, chrome://tracing. @zcbenz PTAL.
Below is a screenshot with `window.location.href="chrome://gpu"`
> Enable webui in content layer.

- browser/inspectable_web_contents_delegate.h
- browser/inspectable_web_contents_impl.cc
- browser/inspectable_web_contents_impl.h
Is there a better way to communicate the event ?
> detecting focus on devtools webcontents

- browser/linux/notification_presenter_linux.cc
- browser/linux/notification_presenter_linux.h
- browser/notification_presenter.h
- browser/notification_presenter_mac.h
- browser/notification_presenter_mac.mm
- browser/platform_notification_service_impl.cc
This PR fixes an issue on Ubuntu where HTML5 notifications would show as modal message boxes. From https://wiki.ubuntu.com/NotificationDevelopmentGuidelines#If_a_notification_is_showing_up_as_an_alert_box:
> Because notification bubbles float on top of all other windows, and usually appear without warning, Notify OSD allows click-through. Hovering over a bubble makes it transparent, and you can click — or drag to or from — anything underneath the bubble. [...] So Notify OSD bubbles cannot be clicked on themselves, nor can they contain buttons that can be clicked: in the terminology of the Desktop Notifications Specification, they do not accept actions. 
This PR also enables you to set the Icon on Linux notifications (this is not possible on OS X, so we no-op it).
Also, I would like to …
> Ubuntu notification improvements

- browser/url_request_context_getter.cc
- browser/url_request_context_getter.h
The `HttpAuthHandlerFactory::CreateDefault` method does not set a URLSecurityManager, so the code will fall-back to disabling all integrated authentication. Instead, use the default URLSecurityManager which will use IE Security Zones on Windows to determine whether a URL is part of the Local Intranet zone or on non-Windows, default proxy rules will be used (i.e. would a default proxy  map vs. connect direct).
> Explicitly create HttpAuthHandlerFactory to enable NTLM / Kerberos authentication

- browser/inspectable_web_contents.h
- browser/inspectable_web_contents_impl.cc
- browser/inspectable_web_contents_impl.h
currently using to set serviceworker agent host to already opened devtools, #80 can also use this as its easy to get agent host for webcontents.
> method to reset devtools agent host

- browser/devtools_ui.cc
These changes bring our copy of devtools_ui.cc in line with https://chromium.googlesource.com/chromium/src.git/+/43.0.2357.92/chrome/browser/ui/webui/devtools_ui.cc
Without these changes, opening the devtools prints errors like:
[0602/165604:ERROR:CONSOLE(0)] "Refused to display 'chrome-devtools://devtools/inspector.html?can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true' in a frame because it set 'X-Frame-Options' to 'DENY'.", source: about:blank (0)
[0602/165604:ERROR:CONSOLE(1514)] "Uncaught SecurityError: Sandbox access violation: Blocked a frame at "chrome-devtools://devtools" from accessing a frame at "null".  The frame being accessed is sandboxed and lacks the "allow-same-origin" flag.", source: chrome-devtools://devtools/devtools.js (1514)
/cc …
> Make devtools work when web security is enabled

- browser/net_log.cc
- browser/net_log.h
- browser/url_request_context_getter.cc
- browser/url_request_context_getter.h
- filenames.gypi
users can now create a net log events dump file and load into `chrome://net-internals` for insight.
> adding support for kLogNetLog switch

- browser/inspectable_web_contents_impl.cc
Related: https://github.com/atom/electron/issues/1901
was unable to reproduce on osx, but from the stack trace it looks like the most likely cause.
/cc @hokein
> fix dereferencing possibly null pointer

- browser/inspectable_web_contents_impl.cc
- browser/inspectable_web_contents_impl.h
The WebContentsDestroyed still access the other members, so if they are
destroyed before the devtools_web_contents_ in the destructor, we will
crash there.
@hokein Can you try if this fixes the crash(https://github.com/atom/electron/issues/1901)?
> Make devtools_web_contents_ is destroyed before everything

- brightray.gypi
This fixes the compilation error in https://github.com/atom/electron/pull/1941
> define openssl_certs on linux

- browser/notification_presenter_mac.mm
This PR avoids a crash on 10.7/10.8 where contentImage is not available
> Ensure we don't try to set notification contentImage on < OS X 10.9

- browser/browser_client.cc
- browser/browser_client.h
- browser/browser_context.cc
- browser/browser_context.h
- browser/net_log.cc
- browser/url_request_context_getter.cc
- browser/url_request_context_getter.h
Fixes https://github.com/atom/electron/issues/1852
Devtools network panel info is based on values extracted from netlog trace in [DevToolsNetLogObserver](https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/devtools/devtools_netlog_observer.h) , so its required to have netlog created and returned in `ContentClient::GetNetLog`.
with this patch devtools network info should be aligned with regular chrome devtools
/cc @zcbenz @hokein
> create netlog instance for devtoolsnetlogobserver

- browser/inspectable_web_contents_impl.cc
- browser/inspectable_web_contents_impl.h
Fixes https://github.com/atom/electron/issues/2324
if its desired to maintain zoom level for all webcontent hosts then could setup preferences in `BrowserContext::ZoomLevelDelegate::InitHostZoomMap` , thoughts ?
> save devtools zoom level preference

- browser/inspectable_web_contents_impl.cc
Fixes https://github.com/atom/electron/issues/2263.
> Don't show devtools window in too small size or out of screen

- browser/inspectable_web_contents_impl.cc
- browser/inspectable_web_contents_view.h
- browser/inspectable_web_contents_view_mac.h
- browser/inspectable_web_contents_view_mac.mm
- browser/mac/bry_inspectable_web_contents_view.h
- browser/mac/bry_inspectable_web_contents_view.mm
- browser/views/inspectable_web_contents_view_views.cc
- browser/views/inspectable_web_contents_view_views.h
This aligns with how chromium treats devtools window title in undocked mode. Havnt tested the osx implmentation. Eases associating a devtools window to the inspected page.
> Allowing devtools window to update title

- browser/permission_manager.cc
PermissionManager should set ChildProcessSecurityPolicy for MIDI SysEx
permission. Otherwise, the browser kills unauthorized renderers that are
going to send MIDI SysEx messages.
Fixes #138.
> Grant ChildProcessSecurityPolicy for MIDI from PermissionManager

- browser/net_log.cc
`log-net-log` switch cant be found before that and hence file never gets created.
> create net log file after context is created

- browser/linux/notification_presenter_linux.cc
This PR fixes the issue in #135 by using the presence of Unity .so files as our canary for detecting Ubuntu's patched notifier (which won't be perfect either sadly, but will pick up more cases). We also add an `ELECTRON_USE_UBUNTU_NOTIFIER` to force this, which users can use if our heuristic fails
Fixes #135
> Rewrite Ubuntu check to look for libunity .so files

- browser/browser_main_parts.cc
- browser/browser_main_parts.h
Chromium ignores X Window System errors, so should we, otherwise Electron will crash when some expected X Window System errors happen.
Fixes https://github.com/atom/electron/issues/1664.
Fixes https://github.com/atom/electron/issues/2844.
Fixes https://github.com/atom/electron/issues/2204.
> Don't crash when X Window System errors happen

- browser/browser_context.cc
- browser/browser_context.h
Don't call virtual function in subclass's constructor.
Fixes atom/electron#2855.
> Fix RegisterPrefs not working in subclass.

- brightray.gyp
https://forums.developer.apple.com/thread/4572 is the best reference I
could find for this.
Apple replaced (some?) dylibs with “text-based stub libraries”
(.tbd’s) in Xcode 7. So we shouldn’t try to reference the dylib directly anymore.
> Don't reference the bsm dylib directly.

- browser/url_request_context_getter.cc
Previously platform dependent on `NSS_CERT_STORE` couldnt follow up on incomplete certificate chain, this fixes it.
Tested with https://incomplete-chain.badssl.com/
> provide request context for oscp session creation

- brightray.gypi
- script/bootstrap
- Currently libchromiumcontent is downloaded by default.
- Now developer can choose to provide local libchromiumcontent src, shared and static path
Tries to solve similar issue noted in: [atom/electron#3310]
> Add option to build local libchromiumcontent

- browser/platform_notification_service_impl.cc
Things aren't pretty on Windows 7, so let's not even try to create a `NotificationPresenter` if we're on Windows 7 or lower.
> Ensure Notifications are Windows 8+ Only

- brightray.gyp
- browser/win/notification_presenter_win.cc
- browser/win/windows_toast_notification.cc
- browser/win/windows_toast_notification.h
We were still missing DLLs on Windows 7 (and therefore refused to launch) - this patch ensures full compatibility with Windows 7.
> Delay Load WinRT Libraries, Full Compat with Windows 7

- browser/win/windows_toast_notification.cc
It was prettier before, but this is better for versions of Windows 7 without various service packs. Once merged, things will be fine even on a virgin/vanilla Windows 7 installation.
(Yes, I consulted a bunch of really old machines from various relatives for this)
> Windows Toasts: Don't call WFI statically

- common/mac/main_application_bundle.mm
Using `IsBackgroundOnlyProcess` is not reliable since the main process can also be a background process. Checking whether process name ends with ` Helper` is obviously not an ideal solution, but if someone is really crazy enough to use `XXX Helper` as their app's name, they can add `ElectronMainProcess` key in `Info.plist` to work around this.
Fix https://github.com/atom/electron/issues/1369.
> Change how Helper process is detected

- browser/net/devtools_network_transaction.cc
- browser/net/devtools_network_transaction.h
- browser/net/devtools_network_transaction_factory.cc
Fixes https://github.com/atom/electron/issues/3831
otherwise accept headers will be set.
Related chromium [issue](https://code.google.com/p/chromium/issues/detail?id=419318)
> devtools: exclude devtools related http header from serviceworker context

- browser/linux/libnotify_loader.cc
- browser/linux/libnotify_loader.h
- browser/linux/notification_presenter_linux.cc
- browser/linux/notification_presenter_linux.h
- filenames.gypi
Instead of linking with libnotify, we now just load the library dynamically, so we no longer need to worry whether a specific version of libnotify exists, and we can avoid possible crashes caused by using wrong version of libnotify.
Fix https://github.com/atom/electron/issues/2294.
> Load libnotify dynamically

- browser/win/notification_presenter_win.cc
- browser/win/notification_presenter_win.h
- browser/win/windows_toast_notification.cc
- browser/win/windows_toast_notification.h
The toast notification of Windows only supports image URLs with `file://` scheme, event data URLs don't work, so in order to have full support of various icon URLs and formats, we have to write the icon into filesystem and then pass the file URL to Windows.
Fix https://github.com/atom/electron/issues/3866.
> Do not use icon url when showing notification

- common/main_delegate.cc
Otherwise devices with scale factor other than 1x will not have the resource loaded.
> Load content_shell.pak for current scale factor

- browser/linux/libnotify_notification.cc
- browser/linux/libnotify_notification.h
- browser/mac/cocoa_notification.h
- browser/mac/cocoa_notification.mm
- browser/notification.h
- browser/platform_notification_service.cc
- browser/win/windows_toast_notification.cc
- browser/win/windows_toast_notification.h
* Implements support for silent notifications on Windows and OS X
* Exposes bool `silent` to Linux notification presenters
Closes https://github.com/atom/electron/issues/4169
> Add Silent Notification Support

- browser/devtools_contents_resizing_strategy.h
- browser/devtools_manager_delegate.cc
- browser/devtools_manager_delegate.h
- browser/inspectable_web_contents_impl.cc
- browser/inspectable_web_contents_impl.h
- browser/media/media_stream_devices_controller.cc
- browser/net/devtools_network_interceptor.cc
- browser/net/devtools_network_transaction.cc
- browser/net/devtools_network_transaction.h
- browser/network_delegate.cc
- browser/network_delegate.h
- browser/permission_manager.cc
- browser/permission_manager.h
- browser/url_request_context_getter.cc
- browser/url_request_context_getter.h
- browser/web_ui_controller_factory.h
- browser/win/scoped_hstring.h
- browser/win/windows_toast_notification.cc
- browser/win/windows_toast_notification.h
> Updates to Chrome 49 on Win32

- browser/win/windows_toast_notification.cc
- Previously, we'd attempt to create a notification no matter what the
user's configuration was. Microsoft advises against that, because it
can create race conditions if notifications are disabled.
- This fixes the issue.
Closes https://github.com/atom/electron/issues/4681
> [Windows] Notify only when enabled

- browser/linux/libnotify_loader.cc
- browser/linux/libnotify_loader.h
- browser/linux/libnotify_notification.cc
- browser/linux/libnotify_notification.h
This is alternative to PR https://github.com/electron/brightray/pull/209 by using a more generic way to verify whether the current notifier supports the `actions` capability or not.
Check the [specs](https://developer.gnome.org/notification-spec/) for more infos.
Fixes https://github.com/electron/electron/issues/465
> Notify check actions cap

- browser/linux/libnotify_notification.cc
- browser/linux/libnotify_notification.h
- browser/mac/cocoa_notification.h
- browser/mac/cocoa_notification.mm
- browser/notification.h
- browser/platform_notification_service.cc
- browser/win/windows_toast_notification.cc
- browser/win/windows_toast_notification.h
LibnotifyNotification: add support for notification tag
We set the id of the notification if tag is provided.
As per the [protocol](https://developer.gnome.org/notification-spec/#protocol), this should cause the old notification with same ID to be replaced.
> Notifications tags

- browser/linux/libnotify_notification.cc
- browser/linux/libnotify_notification.h
- browser/mac/cocoa_notification.h
- browser/mac/cocoa_notification.mm
- browser/mac/notification_center_delegate.mm
- browser/notification.cc
- browser/notification.h
- browser/win/windows_toast_notification.cc
- browser/win/windows_toast_notification.h
On Windows 10 `get_Setting` always returns DISABLED when the program has a AppUserModelID, making notifications never show on it. However if we don't check it the crash in https://github.com/electron/electron/issues/4681 would happen.
This PR solves by removing the `get_Setting` check, and solving https://github.com/electron/electron/issues/4681 by fixing the root cause.
Close https://github.com/electron/electron/issues/4973.
> Fix notification not showing on Windows

- browser/linux/libnotify_loader.cc
- browser/linux/libnotify_loader.h
- browser/linux/libnotify_notification.cc
Use `append` for linux notifications when supported.
This would allow multiple notifications that respects [these rules](https://wiki.ubuntu.com/NotifyOSD#Merging_notifications), to be merged in a single bubble.
Electron developers could prevent this by just providing a notification using an unique `tag` (`new Notification("foo", {tag: unique_id})` would work).
Unfortunately there's no an easy way to allow developers to pass hints to notifications, since the `data` field at seems to be a `SerializedScriptValue` which can't be deserialized at brightray level (without reimplementing some blink internals).
Fixes https://github.com/electron/electron/issues/5052
> Linux notifications append

- brightray.gyp
- browser/linux/libnotify_notification.cc
We are already loading it dynamically there is no meaning linking with the library anymore.
Close https://github.com/electron/electron/issues/5348.
> Do not link with libnotify

- brightray.gyp
It makes executable size smaller and avoids linking with unused shared libraries (e.g. cups).
> Replace --whole-archive with --start-group

- brightray.gyp
Reverts electron/brightray#228.
Closes https://github.com/electron/electron/issues/6178.
It is causing crashes on Linux.
> Revert "Replace --whole-archive with --start-group"

- browser/views/inspectable_web_contents_view_views.cc
On Windows and Linux, `InspectableWebContentsViewViews::IsDevToolsViewFocused` was previously always returning `false` when the devtools are undocked but focused.
This pull request updates it to check the focus state of the devtools windows web view when it is available.
/cc @zcbenz
> Fix IsDevToolsViewFocused on undocked windows

- browser/inspectable_web_contents_impl.cc
- browser/inspectable_web_contents_impl.h
Fixes https://github.com/electron/electron/issues/6156
A side note,
* should `WebDialogHelper::EnumerateDirectory` required to be enumerate over `DIRECTORIES, INCLUDE_DOT_DOT` when its not recursive ?
* The current implementation causes render to terminate with  `RVH_CAN_ACCESS_FILES_OF_PAGE_STATE` because of `INCLUDE_DOT_DOT` in the result.
* Can we make the enumeration async using `net::DirectoryLister` or is the current implementation fine ?
> allow delegate to handle file and color chooser

- brightray.gyp
- browser/inspectable_web_contents_impl.cc
- common/main_delegate.cc
This PR adds the necessary includes to the Chromium content module that are needed for offscreen rendering in Electron.
It depends on a custom *libchromiumcontent* fork, which is also submitted as a [PR](https://github.com/electron/libchromiumcontent/pull/226).
The [PR](https://github.com/electron/electron/pull/6691) in Electron.
> Offscreen rendering support for Electron

- brightray.gyp
- browser/url_request_context_getter.cc
Will encrypt persistent cookies committed after this patch, users will have to update their old cookies to encrypt them.
Depends on https://github.com/electron/libchromiumcontent/pull/229
Fixes https://github.com/electron/electron/issues/7073
> initialize crypto delegate in CookieStoreConfig

- browser/url_request_context_getter.cc
- browser/url_request_context_getter.h
This pull request implements option 3 from #248 to fix the `net::ERR_INSECURE_RESPONSE` error that are happening in Electron 1.4.0 for certain requests.
/cc @deepak1556 @sleevi do you think this is right approach until Brightray can use `URLRequestContextBuilder` directly?
Closes #248
Refs https://github.com/electron/electron/issues/7221
Upstream pull request https://github.com/electron/electron/pull/7292
> Add verifiers for known certificate transparency logs

- browser/url_request_context_getter.cc
- browser/url_request_context_getter.h
Follow up fix for #249 
Looks like there were a few fields only being set on the `net::HttpNetworkSession::Params` and not also set on the `net::URLRequestContextStorage` object that would cause a crash when missing there.
/cc @deepak1556 @sleevi 
Refs https://github.com/electron/electron/issues/7389
> Set CT related fields on URLRequestContextStorage

- README.md
[`brightray_example`](https://github.com/electron-archive/brightray_example) isn't up to date with the latest brightray changes and won't be maintained going forward.
Link directly to Electron as an example of an application using Brightray.
> Link to electron instead of brightray_example

- browser/inspectable_web_contents_impl.cc
settings query param was removed in https://codereview.chromium.org/2177983004 , hence our dock state was not respected. We now directly set the dock state using `WebInspector.dockController.setDockSide` api since it seems more reliable.
Fixes https://github.com/electron/electron/issues/7503
> set dock state using devtools dockController

- browser/linux/libnotify_notification.cc
- browser/mac/cocoa_notification.mm
- browser/notification.h
- browser/platform_notification_service.cc
Previously `cancel_callback` was instantiated after the object it was holding was destroyed, the patch creates notification and sets destructor for `notification.close` api before requesting user permission. Verified on linux only.
Fixes https://github.com/electron/electron/issues/7645
/cc @kevinsawicki @pfrazee
> set notification close callback before requesting user permission

- browser/inspectable_web_contents.h
- browser/inspectable_web_contents_impl.cc
- browser/inspectable_web_contents_impl.h
Fixes https://github.com/electron/electron/issues/8336
The function signatures' where changed to reflect on https://chromium.googlesource.com/chromium/src/+/master/styleguide/c++/c++.md#Object-ownership-and-calling-conventions
> force attach devtools client when requested by inspectable webcontents

- .travis.yml
- appveyor.yml
- script/cibuild
Updates `script/cibuild` and adds configs for Travis and AppVeyor to catch build errors before bumping the submodule in Electron.
`script/cibuild` builds brightray via a full Electron build so all the build options are set correctly.
> Add Travis and AppVeyor CI

- script/bootstrap
Added cwd to the subprocess call as we ended up with the following issue:
In our setup, electron uses submodules based on branches and latest changes (bootstrap scripts are using --remote), but the electron bootstrap is calling brightray bootstrap which was overriding the changes made by the first git sync/update as it was running in the same electron folder.
This change is made so that it does not affect in any way current build process.
> Bootstrap: change working directory when doing submodule updates.

- browser/browser_context.cc
Call `NotifyWillBeDestroyed(this)` and `ShutdownStoragePartitions()` in destructor.
As suggested by @deepak1556 in https://github.com/electron/electron/issues/8563#issuecomment-277227964
Refs https://codereview.chromium.org/653633004
Refs https://codereview.chromium.org/2159133002
Refs https://github.com/electron/electron/issues/8563
> Cleanly shutdown browser context

- browser/inspectable_web_contents_impl.cc
Reverts electron/brightray#278
Refs electron/electron#8817
Seeing the following crash when this spec runs with this change, https://github.com/electron/electron/blob/6d45052eeaf57faf239523b1b328cf37281ae030/spec/webview-spec.js#L1080
```
0   libcontent.dylib                  0x000000011375fd5e content::BrowserPluginGuest::GetOwnerRenderWidgetHostView() + 14
1   libcontent.dylib                  0x0000000113867a53 content::RenderWidgetHostViewGuest::GetNativeView() const + 67
2   libcontent.dylib                  0x0000000113acba6a 0x113433000 + 6916714
3   com.github.electron.framework     0x000000010df41c72 brightray::InspectableWebContentsImpl::CloseDevTools() + 370 (inspectable_web_contents_impl.cc:308)
4   com.github.electron.framework     0x000000010df48e15 …
```
> Revert "close devtools web contents when available to trigger cleanup"

- browser/inspectable_web_contents_impl.cc
The crash has been fixed here https://github.com/electron/electron/pull/8923/commits/72adbf7a2fef7aaef83fb56db9d3e9ddacc99b3a
This reverts commit 7f01bf4e73c188db2406ded1286b661c61c78bba.
> Revert "Revert "close devtools web contents when available to trigger cleanup""

- browser/views/inspectable_web_contents_view_views.cc
- browser/views/inspectable_web_contents_view_views.h
Anonymous namespace should be forbidden in header files even for the forward declarations:
* As declarations defined in anonymous namespace are internal linkage, each translation unit which includes this header will get unique copy, which wastes space.
* It is easy to violate C++ ODR rule.
Consider the following header `foo.h`:
```cpp
namespace { class Foo; }
class Bar {
public:
Foo* getFoo();
Foo* foo;
};
```
If the 'foo.h' is included in multiple `.cc` files, the compiler will put `Foo` into a different anonymous namespace in each `.cc`, which means there are different definitions of `Foo` in the program (a
violation of the ODR).
\cc @deepak1556
> Don't use anonymous namespace in header file.
