electron/brightray

brightray.gypi
See https://github.com/atom/atom-shell/issues/1074 for details.
Not sure if this is the right fix, but with that atom-shell compiles for me.
=> Fix the build on Linux

brightray.gypi
Fixes https://github.com/atom/electron/issues/1653.
=> Turn off incremental linking for Release build

browser/browser_context.cc, browser/browser_context.h, browser/browser_main_parts.h, browser/devtools_embedder_message_dispatcher.cc, browser/devtools_embedder_message_dispatcher.h, browser/devtools_ui.cc, browser/inspectable_web_contents.h, browser/inspectable_web_contents_impl.cc, browser/inspectable_web_contents_impl.h, browser/inspectable_web_contents_view_mac.h, browser/linux/notification_presenter_linux.cc, browser/media/media_capture_devices_dispatcher.h, browser/url_request_context_getter.h, browser/views/inspectable_web_contents_view_views.h, browser/views/views_delegate.h, browser/web_ui_controller_factory.h, common/main_delegate.h
This PR also updates our devtools implementation to match upstream code.
Close https://github.com/atom/electron/issues/1842.
=> Fix networking requests not loading in devtools

browser/browser_context.h, common/content_client.h
ninja compilation failed for me under OS X 10.11
=> Missing overrides

browser/url_request_context_getter.cc
Fixes https://github.com/atom/electron/issues/1599
=> adding support for kProxyPacUrl

browser/mac/bry_inspectable_web_contents_view.h, browser/mac/bry_inspectable_web_contents_view.mm
Fixes https://github.com/atom/electron/issues/2238.
=> Make bottom corner more round

browser/linux/notification_presenter_linux.cc
Fixes https://github.com/atom/electron/issues/2294.
=> Guard against outside input in Linux notifications

brightray.gyp, brightray.gypi, browser/browser_client.cc, browser/browser_client.h, browser/browser_context.cc, browser/browser_context.h, browser/browser_main_parts.cc, browser/browser_main_parts.h, browser/devtools_embedder_message_dispatcher.cc, browser/devtools_embedder_message_dispatcher.h, browser/devtools_manager_delegate.cc, browser/devtools_manager_delegate.h, browser/devtools_ui.cc, browser/inspectable_web_contents_impl.cc, browser/inspectable_web_contents_impl.h, browser/net_log.cc, browser/net_log.h, browser/notification_presenter_mac.h, browser/notification_presenter_mac.mm, browser/platform_notification_service_impl.cc, browser/platform_notification_service_impl.h, browser/url_request_context_getter.cc, browser/url_request_context_getter.h, common/content_client.cc, common/content_client.h
=> Upgrade to Chrome 44

browser/inspectable_web_contents_impl.cc, browser/inspectable_web_contents_view.h, browser/inspectable_web_contents_view_mac.h, browser/inspectable_web_contents_view_mac.mm, browser/mac/bry_inspectable_web_contents_view.h, browser/mac/bry_inspectable_web_contents_view.mm, browser/views/inspectable_web_contents_view_views.cc, browser/views/inspectable_web_contents_view_views.h
Refs https://github.com/atom/electron/issues/981.
=> Add IsDevToolsViewFocused method and make DevToolsFocused work in OS X

browser/inspectable_web_contents_impl.cc
As of this [CL](https://codereview.chromium.org/1187743003) a few of devtools frontend modules have been moved to remote URL and are not available in the bundle unless built with `debug_devtools` switch. The fix is to provide a `remoteBase` as a query parameter for devtools URL. Have taken same remoteBase chrome devtools relies on.
Fixes https://github.com/atom/electron/issues/2851
/cc @zcbenz
=> provide remoteBase to load remote devtools modules

browser/views/views_delegate.cc
Closes https://github.com/atom/electron/issues/877.
=> Fix tooltip cropped by the window on Linux

browser/url_request_context_getter.cc
Fixes https://github.com/atom/electron/issues/3034
=> set accept-language header from system locale

script/bootstrap
- appending the args correctly
- creating the target directory if does not exist
=> Fix build error

browser/win/windows_toast_notification.cc
We should probably have tests for Windows notifications ;-)
=> Fix Tag Typo

browser/win/notification_presenter_win.cc, browser/win/windows_toast_notification.cc, browser/win/windows_toast_notification.h
Close #176.
Close https://github.com/atom/electron/issues/3493.
=> Use AppUserModelID as app id

browser/win/notification_presenter_win.cc, browser/win/scoped_hstring.cc, browser/win/scoped_hstring.h, browser/win/windows_toast_notification.cc, browser/win/windows_toast_notification.h
Close https://github.com/atom/electron/issues/3458.
=> Use application name when app user model ID is not available

browser/url_request_context_getter.cc
This PR adds support for the `--proxy-bypass-list` command line argument. It enables you to decide on hosts that should bypass the proxy server set by `--proxy-server`. For example if your app talks to a local web server (e.g. http://127.0.0.1:8080), you probably don't want it to go through the proxy server (how will it resolve 127.0.0.1 to the correct host?), so you can use `--proxy-bypass-list="127.0.0.1:8080"` or the more general `--proxy-bypass-list="<local>"`.
The value can contain more than one host, separated by semi-colon. See examples at: https://www.chromium.org/developers/design-documents/network-settings
Related Electron PR for docs: atom/electron#3550.
=> Add support for --proxy-bypass-list

brightray.gyp, brightray.gypi
=> Desktop capture API support

browser/url_request_context_getter.cc
Fixes https://github.com/atom/electron/issues/3720
=> add list of next_protos to use

browser/devtools_manager_delegate.cc
Fixes https://github.com/atom/electron/issues/3780
=> fix value of IDR_CONTENT_SHELL_DEVTOOLS_DISCOVERY_PAGE

brightray.gyp
It depends on the pull request https://github.com/atom/libchromiumcontent/pull/162
=> Add widevine third party

browser/devtools_embedder_message_dispatcher.h, browser/inspectable_web_contents_delegate.h, browser/inspectable_web_contents_impl.cc, browser/inspectable_web_contents_impl.h
Changes introduced in https://codereview.chromium.org/1375323005
=> fix devtools filesystem api

browser/browser_main_parts.cc
Fixes https://github.com/electron/electron/issues/4931
=> register localized media strings

browser/browser_context.cc, browser/browser_context.h, browser/net/devtools_network_controller_handle.cc, browser/net/devtools_network_controller_handle.h, browser/net/devtools_network_interceptor.cc, browser/net/devtools_network_protocol_handler.cc, browser/net/devtools_network_transaction.cc, browser/url_request_context_getter.cc, browser/url_request_context_getter.h, filenames.gypi
Fixes https://github.com/electron/electron/issues/5121
Ported from https://codereview.chromium.org/1279603002
=> Fix race initialising DevtoolsNetworkController

browser/browser_main_parts.cc, browser/browser_main_parts.h
Depends on https://github.com/electron/libchromiumcontent/pull/215
=> initialize bluetooth for linux

browser/inspectable_web_contents_impl.cc
Close https://github.com/electron/electron/issues/4261.
=> Fix double free when closing window with devtools opened

browser/mac/bry_inspectable_web_contents_view.mm, browser/mac/event_dispatching_window.h, browser/mac/event_dispatching_window.mm, filenames.gypi
See https://github.com/electron/electron/pull/6068 for more details
=> Redispatch key events to handle native shortcuts

browser/browser_client.h, browser/platform_notification_service.cc
Required for electron/electron/pull/6313
=> Patch OnWebNotificationAllowed to mark notifications as silent in muted WebContents

browser/inspectable_web_contents_impl.cc
Close https://github.com/electron/electron/issues/2565.
=> Allow devtools window to show on other screens

browser/url_request_context_getter.cc, browser/url_request_context_getter.h
See https://github.com/electron/electron/pull/7398 for more details.
=> Support configuring a cookie delegate

browser/inspectable_web_contents_impl.cc
Ref https://github.com/electron/brightray/pull/254#issuecomment-252742191
/cc @kevinsawicki
=> use dock state from peferences when not set by embedder

browser/browser_context.cc, browser/browser_context.h, browser/media/media_device_id_salt.cc, browser/media/media_device_id_salt.h, browser/url_request_context_getter.h, filenames.gypi
Fixes https://github.com/electron/electron/issues/8135
=> persist media device id salt across sessions

browser/net/devtools_network_interceptor.cc
When download and upload throughout are set to their default values, the timer would compute negative delay and keep spinning forever. There was no problem with emulation from devtools because latency, download throughput and upload throughput are always specified.
Fixes https://github.com/electron/electron/issues/8203
=> interceptor should handle default values of download and upload throughput

browser/inspectable_web_contents_impl.cc
=> Update std:move call to fix macOS compiler error

browser/inspectable_web_contents_impl.cc
Fixes https://github.com/electron/electron/issues/8817
=> close devtools web contents when available to trigger cleanup

browser/browser_client.cc, browser/browser_main_parts.cc, browser/browser_main_parts_mac.mm, browser/devtools_file_system_indexer.cc, browser/inspectable_web_contents_view_mac.mm, browser/mac/bry_inspectable_web_contents_view.mm, browser/net/devtools_network_controller.cc, browser/net/devtools_network_interceptor.cc, browser/web_ui_controller_factory.cc, common/application_info_mac.mm
=> Cleanup codebase

browser/browser_main_parts.cc, browser/browser_main_parts.h
See:
https://chromium.googlesource.com/chromium/src/+/cd4f72fdeae5d12e0c7c4efc0a1a0e1d7af1e0ba/ui/views_content_client/views_content_client_main_parts_aura.cc#23
This fixes electron/electron#9197.
=> Initialize wm::WMState on Windows as well
